name: CD build

on:
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.NOMBRE_BASE }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: desa
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ vars.NOMBRE_BASE }}

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
         echo "Construyendo la imagen con la etiqueta: $IMAGE_NAME:$IMAGE_TAG"
         docker build -f src/main/docker/Dockerfile.jvm -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          echo "Desplegando la imagen: $IMAGE_NAME:$IMAGE_TAG"
          docker push $IMAGE_NAME:$IMAGE_TAG