name: CD Docker Deploy

on:
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.NOMBRE_BASE }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: desa

    permissions:
      contents: read
      actions: read
    steps:
      - name: Obtener ID del último build exitoso
        id: get-run-id
        run: |
          CI_RUN_ID=$(curl -s \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.TOKEN }}" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/ci.yml/runs?branch=${{ github.event.inputs.deploy_branch }}&status=success" \
          | jq '.workflow_runs[0].id')
          
          if [ -z "$CI_RUN_ID" ]; then
            echo "Error: No se encontró una ejecución de CI exitosa para la rama '${{ github.event.inputs.deploy_branch }}'."
            exit 1
          fi
          
          echo "run_id=$CI_RUN_ID" >> $GITHUB_OUTPUT
          echo "ID de ejecución de CI encontrado: $CI_RUN_ID"

      - name: Pull Artifact
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          run-id: ${{ steps.get-run-id.outputs.run_id }}
          path: target

      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.deploy_branch }}

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: |
          echo "Construyendo la imagen con la etiqueta: $IMAGE_NAME:$IMAGE_TAG"
          docker build -f src/main/docker/Dockerfile.jvm -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Push Docker image
        run: |
          echo "Desplegando la imagen: $IMAGE_NAME:$IMAGE_TAG"
          docker push $IMAGE_NAME:$IMAGE_TAG