name: Deploy

on:
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.NOMBRE_BASE }}

jobs:
  deploy_job:
    name: Construir y subir Docker
    runs-on: ubuntu-latest
    environment: desa
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Pull Artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ci.yml
          name: app-artifact
          path: target
          repo: ${{ github.repository }}

      - name: Obtener el SHA corto de commit
        id: short-sha
        uses: benjlevesque/short-sha@v3.0

      - name: Sanitizar nombre de la rama
        id: branch_name
        run: |
          SANITIZED_BRANCH=$(echo "${{ github.ref_name }}" | sed 's/\//-/g')
          echo "sanitized_branch=${SANITIZED_BRANCH}" >> $GITHUB_OUTPUT

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen
        run: |
          IMAGE_TAG="${{ steps.branch_name.outputs.sanitized_branch }}-${{ steps.short-sha.outputs.sha }}"
          echo "Construyendo la imagen: ${{ env.IMAGE_NAME }}:${IMAGE_TAG}"
          docker build . -t ${{ env.IMAGE_NAME }}:${IMAGE_TAG}
          docker push ${{ env.IMAGE_NAME }}:${IMAGE_TAG}