name: Deploy

on:
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.NOMBRE_BASE }}

jobs:
  deploy_job:
    name: Construir y subir Docker
    runs-on: ubuntu-latest
    environment: desa
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Descargar artefacto del último run
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ci.yml
          name: app-artifact
          path: target
          repo: ${{ github.repository }}

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir imagen
        run: |
          echo "Construyendo la imagen: $IMAGE_NAME:$IMAGE_TAG"
          docker build -f src/main/docker/Dockerfile.jvm -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG