name: CI build

on:
  workflow_dispatch:
  push:
    branches: [ feature/**, release/** ]
  pull_request:
    branches: [ main, develop, release/**]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: desa
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build
        run: ./mvnw clean install

      - name: Deploy
        run: docker build -f src/main/docker/Dockerfile.jvm -t ${{ vars.NOMBRE_BASE }}${{ github.sha }} .