name: CI

on:
  push:
    branches: [ feature/**, release/** ]
  pull_request:
    branches: [ main, develop, release/** ]

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.NOMBRE_BASE }}

jobs:
  build_job:
    name: Compilar la app
    runs-on: ubuntu-latest
    environment: desa
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Compilar con Maven
        run: ./mvnw clean install

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: target