name: CI/CD

on:
  push:
    branches: [ feature/**, release/** ]
  pull_request:
    branches: [ main, develop, release/**]
  workflow_dispatch:
    inputs:
      deploy_branch:
        description: 'La rama a desplegar (ej. release/v1.0.0)'
        required: false
        type: string
        default: 'feature/pipe-docker'

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.NOMBRE_BASE }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: desa
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
         ref: ${{ github.event.inputs.deploy_branch != '' && github.event.inputs.deploy_branch || github.ref }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Compilar con Maven
        run: ./mvnw clean install

      - name: Login Docker Hub
        if: github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir y subir la imagen de Docker
        if: github.event_name == 'workflow_dispatch'
        run: |
          echo "Construyendo la imagen con la etiqueta: $IMAGE_NAME:$IMAGE_TAG"
          docker build -f src/main/docker/Dockerfile.jvm -t $IMAGE_NAME:$IMAGE_TAG .
          echo "Desplegando la imagen: $IMAGE_NAME:$IMAGE_TAG"
          docker push $IMAGE_NAME:$IMAGE_TAG