## A basic GitHub Actions workflow for your Quarkus application.

name: CI build

on:
  push:
    branches: [ feature/pipe-docker ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build
        run: ./mvnw clean install

      - name: Deploy
        run: docker build -f src/main/docker/Dockerfile.jvm -t ${NOMBRE_BASE}:$(date +%s) .