name: CI build

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Branch to run the pipeline on'
        required: true
        type: string
  push:
    branches: [ feature/**, release/** ]
  pull_request:
    branches: [ main, develop, release/**]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: desa
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.deploy }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Install
        run: ./mvnw clean install

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        run: docker build -f src/main/docker/Dockerfile.jvm -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.NOMBRE_BASE }}${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push  ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.NOMBRE_BASE }}${{ github.sha }}