name: CI build

on:

  push:
    branches: [ feature/**, release/** ]
  pull_request:
    branches: [ main, develop, release/**]

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.NOMBRE_BASE }}
jobs:
  build:
    runs-on: ubuntu-latest
    environment: desa
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.deploy }}

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Install
        run: ./mvnw clean install

      - name: Push artifact
        uses: actions/upload-artifact@v4
        with:
          name: $IMAGE_NAME
          path: target/*.jar