name: CI/CD

on:
  push:
    branches: [ feature/**, release/** ]
  pull_request:
    branches: [ main, develop, release/** ]
  workflow_dispatch:

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.NOMBRE_BASE }}

jobs:
  build_job:
    name: Compilar la app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build Maven
        run: ./mvnw clean install

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-artifact
          path: target

  deploy_job:
    name: Push Docker
    needs: build_job
    if: github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Descargar artefacto
        uses: actions/download-artifact@v4
        with:
          name: app-artifact
          path: target

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          echo "Construyendo la imagen: $IMAGE_NAME:$IMAGE_TAG"
          docker build -f src/main/docker/Dockerfile.jvm -t $IMAGE_NAME:$IMAGE_TAG .
          docker push $IMAGE_NAME:$IMAGE_TAG